# Generated by Django 3.2.8 on 2021-10-24 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_qualification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='name',
            new_name='qualification',
        ),
    ]
