# Generated by Django 3.2.8 on 2021-10-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Mental Health Specialist', 'Mental Health Specialist'), ('User', 'User')], default='User', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
