# Generated by Django 3.2.8 on 2021-10-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211029_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Mental Health Specialist', 'Mental Health Specialist'), ('User', 'User')], default='Select your role', max_length=50, null=True),
        ),
    ]
