# Generated by Django 3.2.8 on 2021-11-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_profile_social_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='confirm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
