# Generated by Django 3.2.8 on 2021-11-09 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_appointment_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_appointments', to='users.profile'),
        ),
    ]
