# Generated by Django 3.2.8 on 2021-11-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_appointment_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-confirm', 'date']},
        ),
    ]
