# Generated by Django 3.2.8 on 2021-10-20 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20211019_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
