# Generated by Django 3.2.8 on 2021-11-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_remove_blog_demo_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='source_link',
            new_name='video_link',
        ),
    ]
