# Generated by Django 3.2.8 on 2021-10-26 16:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayDescription',
            fields=[
                ('date', models.DateField(auto_created=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
            options={
                'unique_together': {('owner', 'date')},
            },
        ),
    ]
