# Generated by Django 3.2.8 on 2021-10-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydescription',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
