# Generated by Django 3.2.8 on 2021-10-29 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211029_2302'),
        ('tracker', '0002_alter_daydescription_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydescription',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='users.profile'),
        ),
    ]
