# Generated by Django 3.2.8 on 2021-10-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_daydescription_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydescription',
            name='date',
            field=models.DateField(),
        ),
    ]
