# Generated by Django 3.2.8 on 2021-10-29 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_daydescription_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daydescription',
            options={'ordering': ['date']},
        ),
    ]
