# Generated by Django 3.2.8 on 2021-11-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_daydescription_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydescription',
            name='date',
            field=models.DateField(),
        ),
    ]
