# Generated by Django 3.2.8 on 2021-11-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_daydescription_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydescription',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
